django3/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import views
from user_auth.views import user_login





urlpatterns = [
    
    path('', user_login, name='login'),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('user_auth/', include('user_auth.urls')),
   
   
 

    
   
    
]

polls/urls.py
from django.urls import path, include
from . import views
from django.urls import re_path

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    re_path(r'^polls/(?P<question_id>[0-9]+)/$', views.detail, name='detail')
]

user_auth/urls.py
# user_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'user_auth'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('', views.user_login, name='login_old'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('show_user/', views.show_user, name='show_user'),
    path('register/', views.register, name='register'),
    path('registration_success/', views.registration_success, name='registration_success'),
    
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

user_auth/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/poll.html", context)



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )
    except (KeyError, Choice.DoesNotExist):
# Redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
# Always return an HttpResponseRedirect after successfully
# dealing with POST data. This prevents data from being
# posted twice if a
# user hits the Back button.
        return HttpResponseRedirect(
            reverse('polls:results', args=(question_id,))

        )

user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login

def user_login(request):
    return render(request, 'authentication/login.html')

class CustomLoginView(LoginView):
    template_name = 'authentication/login.html'
    authentication_form = AuthenticationForm

def authenticate_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('polls:index')
        else:
            return render(request, 'authentication/login.html', {'error': 'Invalid login credentials'})
    else:
        return redirect('user_auth:login')

def show_user(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            return redirect('polls:index')
        else:
            return render(request, 'authentication/user.html', {'user': request.user})
    else:
        return redirect('user_auth:login')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user_auth:registration_success')
    else:
        form = UserCreationForm()
    return render(request, 'authentication/register.html', {'form': form})

def registration_success(request):
    return render(request, 'authentication/registration_success.html')

polls/templates/polls/detail.html
<div class="container">
    <h1>{{question.question_text}}</h1>

    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            <strong>{{error_message}}</strong>
        </div>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% if question.choice_set.all %}
                <p>Choices found for the question</p>
            {% else %}
                <p>No choices found for the question</p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                    <label class="form-check-label" for="choice{{ forloop.counter }}">
                        {{ choice.choice_text }}
                    </label>
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Vote</button>
    </form>
</div>

<!-- Bootstrap CDN links -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

polls/templates/polls/poll.html
{% if latest_question_list %}
<ul class="list-group">
    {% for question in latest_question_list %}
    <li class="list-group-item">
        <a href="{% url 'polls:detail' question.id %}">
        {{ question.question_text }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<div class="alert alert-info" role="alert">
    No polls are available.
</div>
{% endif %}

<!-- Bootstrap CDN links -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

polls/templates/polls/results.html
<div class="container">
    <h1>{{ question.question_text }}</h1>

    <ul class="list-group">
        {% for choice in question.choice_set.all %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ choice.choice_text }}
            <span class="badge badge-primary badge-pill">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary mt-3">Vote again?</a>
</div>

<!-- Bootstrap CDN links -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

user_auth/templates/authentication/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<h1>Login as User</h1>
				<form action="{% url 'user_auth:authenticate_user' %}" method="post">
				    {% csrf_token %}

				    <div class="form-group">
				        <label for="username">Username</label>
				        <input type="text" class="form-control" name="username" placeholder="User" required>
				    </div>

				    <div class="form-group">
				        <label for="password">Password</label>
				        <input type="password" class="form-control" name="password" required>
				    </div>

				    <button type="submit" class="btn btn-primary">Login</button>
				</form>
			</div>
		</div>
	</div>
</body>
</html>

user_auth/templates/authentication/registration.html
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

user_auth/templates/authentication/user.html
<h1>Welcome, {{ username }}</h1>
<p>Your password is {{ user.password }}</p>